# Generated by Django 3.0.8 on 2020-07-05 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser_agent_api', '0002_collect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='response',
        ),
    ]
