# Generated by Django 3.0.8 on 2020-07-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser_agent_api', '0003_remove_collect_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.CharField(max_length=20)),
                ('Response', models.CharField(max_length=200)),
                ('DomainName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='Collect',
        ),
    ]
