# Generated by Django 3.0.8 on 2020-07-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser_agent_api', '0004_auto_20200709_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='inform',
            name='Type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
