# Generated by Django 3.0.8 on 2020-07-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser_agent_api', '0005_inform_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='DomainName',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
